apiVersion: v1
kind: Service # Kubernetes Service definition
metadata:
  name: clothing-classifier # name of the service
spec:
  type: NodePort # service type
  selector:
    app: clothing-classifier # 
  ports: 
  - protocol: TCP  # 
    port: 8080 # service port
    targetPort: 8080 # target port on the pod
    nodePort: 30080 # node port for external access